# Generated by Django 5.1.4 on 2025-01-31 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('theme', models.CharField(default='basic', max_length=20)),
                ('is_temp_save', models.BooleanField(default=False)),
                ('video_id', models.CharField(max_length=50, null=True)),
                ('thumbnail_url', models.URLField(default='')),
                ('music_title', models.CharField(default='알 수 없음', max_length=50)),
                ('artist', models.CharField(default='알 수 없음', max_length=30)),
                ('like_users', models.ManyToManyField(blank=True, related_name='like_diary', to='accounts.profile')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='diary.comment')),
                ('writer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.profile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='diary.diary')),
            ],
        ),
    ]
