# Generated by Django 5.1.4 on 2025-01-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_profile_img'),
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='like_users',
            field=models.ManyToManyField(related_name='like_diary', to='accounts.profile'),
        ),
    ]
