# Generated by Django 5.1.4 on 2025-02-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='artist',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='diary',
            name='music_title',
            field=models.CharField(max_length=50),
        ),
    ]
