# Generated by Django 5.1.4 on 2025-01-23 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_profile_img'),
        ('diary', '0002_diary_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='thumbnail_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='diary',
            name='video_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to='accounts.profile'),
        ),
    ]
