# Generated by Django 5.1.4 on 2025-01-23 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_profile_img'),
        ('diary', '0003_diary_thumbnail_url_diary_video_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='writer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_diary', to='accounts.profile'),
        ),
    ]
