# Generated by Django 5.1.4 on 2025-01-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_alter_comment_writer_alter_diary_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='artist',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='diary',
            name='music_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
