# Generated by Django 5.1.4 on 2025-01-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_diary_artist_diary_music_title_alter_diary_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='artist',
            field=models.CharField(default='알 수 없음', max_length=30),
        ),
        migrations.AlterField(
            model_name='diary',
            name='music_title',
            field=models.CharField(default='알 수 없음', max_length=50),
        ),
    ]
