# Generated by Django 5.1.4 on 2025-01-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_alter_diary_artist_alter_diary_music_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='is_temp_save',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diary',
            name='thumbnail_url',
            field=models.URLField(default=' '),
        ),
        migrations.AlterField(
            model_name='diary',
            name='video_id',
            field=models.CharField(blank=True, default=' ', max_length=50),
        ),
    ]
