# Generated by Django 5.1.4 on 2025-01-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_diary_is_temp_save_alter_diary_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='thumbnail_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='diary',
            name='video_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
