# Generated by Django 5.1.4 on 2025-01-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_alter_diary_thumbnail_url_alter_diary_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='diary',
            name='create_at',
            field=models.DateTimeField(),
        ),
    ]
