# Generated by Django 5.1.4 on 2025-01-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0012_alter_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='theme',
            field=models.CharField(default='기타', max_length=20),
        ),
    ]
