# Generated by Django 5.1.4 on 2025-01-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0013_diary_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='theme',
            field=models.CharField(default='basic', max_length=20),
        ),
    ]
