# Generated by Django 5.1.4 on 2025-01-21 06:45

import utils.file_upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_followings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='profiles/images/default.png', upload_to=utils.file_upload.user_dir_path),
        ),
    ]
