# Generated by Django 5.1.4 on 2025-01-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
    ]
